# action.yml
name: 'Pub-2-PyPI'
description: 'Publish a package to PyPI after performing some customizeable checks.'
#inputs:
#  git_tag:  # id of input
#    description: 'Print this string'
#    required: true
#    default: 'World'
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
#  args:
#    - ${{ inputs.git_tag }}

